USER_PASSWORD_LEN: int = 3
MIN_LENGTH: int = 1
FULLY_INVESTED_FALSE: int = 0
FULLY_INVESTED_TRUE: int = 1
MAX_LENGTH: int = 100
COLUMN: int = 11
EXAMPLE_VALUE: int = 1350
JWT_SECONDS_LIMIT: int = 3600
